plugins:
  translator_enabled:
    default: false
    client: true
  translator:
    default: 'Microsoft'
    client: true
    type: enum
    choices:
      - Microsoft
      - Google
  translator_client_id:
    default: ''
  translator_client_secret:
    default: ''
  azure_subscription_key:
    default: ''
  translator_google_api_key:
    default: ''
