plugins:
  translator_enabled:
    default: false
    client: true
  translator:
    default: 'Microsoft'
    client: true
    type: enum
    choices:
      - Microsoft
      - Google
      - Amazon
      - Yandex
      - LibreTranslate
  translator_azure_subscription_key:
    default: ''
  translator_azure_region:
    default: 'global'
    client: true
    type: enum
    choices: # Valid choices retrieved from https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference#authenticating-with-a-multi-service-resource
      - global
      - australiaeast
      - brazilsouth
      - canadacentral
      - centralindia
      - centralus
      - centraluseuap
      - eastasia
      - eastus
      - eastus2
      - francecentral
      - japaneast
      - japanwest
      - koreacentral
      - northcentralus
      - northeurope
      - southafricanort
      - southcentralus
      - southeastasia
      - uksouth
      - westcentralus
      - westeurope
      - westus
      - westus2
  translator_aws_region:
    default: 'us-east-1'
    client: true
    type: enum
    choices: # Valid choices retrieved from https://docs.aws.amazon.com/general/latest/gr/rande.html#translate_region
      - us-east-2
      - us-east-1
      - us-west-1
      - us-west-2
      - af-south-1
      - ap-east-1
      - ap-south-1
      - ap-northeast-3
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ap-northeast-1
      - ca-central-1
      - cn-north-1
      - cn-northwest-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-south-1
      - eu-west-3
      - eu-north-1
      - me-south-1
      - sa-east-1
  translator_aws_key_id:
    default: ''
  translator_aws_secret_access:
    default: ''
  translator_aws_iam_role:
    default: ''
  translator_google_api_key:
    default: ''
  translator_yandex_api_key:
    default: ''
  translator_libretranslate_endpoint:
    default: ''
  translator_libretranslate_api_key:
    default: ''
  max_translations_per_minute:
    default: 3
